[#_contribution_guidelines]
= Contribution Guidelines
:toc:
:toclevels: 3
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[#_naming_scheme]
== Naming Scheme

[cols=">,<,<",options="header",]
|===
|Scope |Scheme | Remarks

|Files
|PascalScheme
|

|Functions
|camelCase
|

|Variables
|camelCase
|suffix: typedef => `_t`

|Preprocessor
|SCREAMING_SNAKE_CASE
|
|===

Functions and global variables should be prefixed with a consistent identifier, e.g.the file name where the function prototype resides.

[#_code_contributions]
== Code Contributions

[IMPORTANT]
====
Don’t push directly to the `main` branch::
- Push your modification to a new branch
- Open a pull request to `main`
- The maintainer of the repository can then merge your modifications into the existing codebase
====

== Workflow

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
----
gitGraph
    commit
    branch release_canidate
    branch develop
    commit
    branch xxx-feature
    commit
    commit
    commit
    checkout develop
    merge xxx-feature
    checkout develop
    branch yyy-feature
    commit
    commit
    checkout develop
    merge yyy-feature
    checkout release_canidate
    merge develop
    commit
    checkout main
    merge release_canidate
----

NOTE: If you want to develop a new feature, or contribute new source code, you are required branch out from the develop branch with your own feature branch This branch will then be merged back into the develop branch via a Pull-Request.


CAUTION: Before merging to `main` it is important to change the enV5 Tag inside the `helpers.cmake` to the latest release Tag!

[#_commit_messages]
== Commit Messages

We use https://spin.atomicobject.com/conventional-commits/[conventional commits]

NOTE: To ensure our guidelines we suggest to use Pre-Commit as described in the link:./Setup_Guide.adoc#_pre_commit_optional[Setup Guide].

